name: CI

on:
  push:

jobs:

  ci:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: cd s3-agent && go mod verify

    - name: Build
      run: cd s3-agent && make rclone && go build -v

    - name: Run go vet
      run: cd s3-agent && go vet

    - name: Install golint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

    - name: Run golint
      run: cd s3-agent && golangci-lint run --fast

    - name: Run tests
      run: cd s3-agent && go test -race -vet=off
