name: CI

on:
  push:

jobs:

  ci:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: cd s3-agent && go mod verify

    - name: Build
      run: cd s3-agent && make rclone && go build -v

    - name: Run go vet
      run: cd s3-agent && go vet

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: cd s3-agent && golint

    - name: Run tests
      run: cd s3-agent && go test -race -vet=off
