name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release:
        name: Release Go Binary
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Get tag version
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.RELEASE_VERSION }}
                  release_name: Release ${{ env.RELEASE_VERSION }}
                  draft: false
                  prerelease: false

            - name: Release Go binary
              uses: wangyoucao577/go-release-action@v1.29
              with:
                  pre_command: make rclone
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  goos: linux
                  goarch: amd64
                  release_tag: ${{ env.RELEASE_VERSION }}
                  project_path: "./s3-agent"
